"use strict";

const fs = require("fs");
const path = require("path");
const { readTextIfExists } = require("@mantle-forge/cli-utils");

function listSolidityContracts(contractsDir) {
  if (!fs.existsSync(contractsDir)) return [];
  return fs
    .readdirSync(contractsDir)
    .filter((name) => name.endsWith(".sol"))
    .sort();
}

function readJsonIfExists(filePath) {
  const text = readTextIfExists(filePath);
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

function formatDeployment(deployment) {
  if (!deployment) return "_No deployment artifact found (`deployments/mantleSepolia.json`)._\n";

  const lines = [
    `- Network: ${deployment.network || "mantleSepolia"}`,
    `- Chain ID: ${deployment.chainId || 5003}`,
  ];

  if (deployment.contracts) {
    for (const [name, info] of Object.entries(deployment.contracts)) {
      lines.push(`- **${name}**: \`${info.address}\``);
      if (info.txHash) lines.push(`  - Tx: \`${info.txHash}\``);
    }
  }

  if (deployment.verification?.contracts) {
    lines.push("", "**Mantlescan verification:**");
    for (const [name, info] of Object.entries(deployment.verification.contracts)) {
      lines.push(`- **${name}**: ${info.status}${info.onChainVerified === true ? " (confirmed on explorer)" : ""}`);
      if (info.explorerUrl) lines.push(`  - ${info.explorerUrl}`);
      if (info.error && info.status === "failed") {
        lines.push(`  - Error: ${info.error.split("\n")[0]}`);
      }
    }
  }

  if (deployment.explorer) {
    for (const [label, url] of Object.entries(deployment.explorer)) {
      lines.push(`- Explorer (${label}): ${url}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function buildReport(projectDir, options = {}) {
  const root = path.resolve(projectDir);
  const projectName = options.projectName || path.basename(root);
  const packageJson = readJsonIfExists(path.join(root, "package.json"));
  const contracts = listSolidityContracts(path.join(root, "contracts"));
  const security = readTextIfExists(path.join(root, "reports", "security.md"));
  const gas = readTextIfExists(path.join(root, "reports", "gas.md"));
  const deployment = readJsonIfExists(path.join(root, "deployments", "mantleSepolia.json"));
  const testSummary = readTextIfExists(path.join(root, "reports", "test-summary.md"));

  const missing = [];
  if (!security) missing.push("reports/security.md");
  if (!gas) missing.push("reports/gas.md");
  if (!deployment) missing.push("deployments/mantleSepolia.json");

  const sections = [
    "# FINAL_REPORT",
    "",
    "## Project",
    "",
    `- **Name:** ${packageJson?.name || projectName}`,
    `- **Path:** \`${root}\``,
    "",
    "### Contracts",
    "",
    contracts.length
      ? contracts.map((c) => `- \`contracts/${c}\``).join("\n")
      : "_No Solidity contracts found._",
    "",
    "## Test results",
    "",
    testSummary || "_No test summary found. Run `npx hardhat test` and optionally save output to reports/test-summary.md._",
    "",
    "## Security review",
    "",
    security ||
      "_Missing reports/security.md — run agent-assisted security review or `mantle-audit`._",
    "",
    "## Gas analysis",
    "",
    gas || "_Missing reports/gas.md — run gas analysis or `mantle-gas-report`._",
    "",
    "## Deployment",
    "",
    formatDeployment(deployment),
    "## Next improvements",
    "",
    missing.length
      ? missing.map((item) => `- Add ${item}`).join("\n")
      : "- Optional: frontend for contract interactions",
    "",
    "## Execution log reference",
    "",
    `- Generated by \`mantle-report\` on ${new Date().toISOString()}`,
    "- Review agent-assisted security wording — not a professional audit.",
    "",
  ];

  return {
    markdown: sections.join("\n"),
    missing,
    projectDir: root,
  };
}

function writeReport(projectDir, outPath, options = {}) {
  const { markdown, missing } = buildReport(projectDir, options);
  const target = path.resolve(outPath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, markdown, "utf8");
  return { outPath: target, missing };
}

module.exports = { buildReport, writeReport, listSolidityContracts };
